name: CI

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Select build type"
        required: true
        default: "both"
        type: choice
        options:
          - debug
          - release
          - both

  pull_request:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

  push:
    paths-ignore:
      - "README*.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      # ---------- BUILD ----------
      - name: Build Debug APK
        if: ${{ github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == 'both' }}
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: ${{ github.event.inputs.build_type == 'release' || github.event.inputs.build_type == 'both' }}
        run: ./gradlew assembleRelease

      # ---------- RELEASE SIGN (NO PC REQUIRED) ----------
      - name: Generate Keystore
        if: ${{ github.event.inputs.build_type == 'release' || github.event.inputs.build_type == 'both' }}
        run: |
          keytool -genkeypair \
            -alias ${{ secrets.KEY_ALIAS }} \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore release.keystore \
            -storepass ${{ secrets.KS_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            -dname "CN=CI, OU=Android, O=LibreTube, L=Internet, S=World, C=IN"

      - name: Sign Release APK
        if: ${{ github.event.inputs.build_type == 'release' || github.event.inputs.build_type == 'both' }}
        run: |
          APK=$(find app/build/outputs -name "*release*.apk" | head -n 1)

          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks release.keystore \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KS_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out signed-release.apk \
            $APK

      # ---------- UPLOAD ----------
      - name: Upload Debug APK
        if: ${{ github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == 'both' }}
        uses: actions/upload-artifact@v6
        with:
          name: debug-apk
          path: app/build/outputs/**/debug/*.apk
          if-no-files-found: warn

      - name: Upload Release APK
        if: ${{ github.event.inputs.build_type == 'release' || github.event.inputs.build_type == 'both' }}
        uses: actions/upload-artifact@v6
        with:
          name: release-apk
          path: signed-release.apk
